spring:
  application:
    name: spring-reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: password
    #r2dbc doesn't support database creation and table creation
  flyway:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: password